### ISSUE TITLE
Unable to connect to PsyPad Server

### ISSUE THREAD

**Issue by jhamwood** [davidlawson/PsyPad#15]
10.5 inch iPad Pro on iOS 12.1.3 is unable to log in to PsyPad account, with a NSURLErrorDomain error -1012 on attempted log in. 

9.7 inch iPad on iOS 10.3.3 on the same network is able to connect and upload tests as intended.

A third iPad Pro on a different network is able to log in, but experienced delays on uploading tests until 4th February 2019, after which uploads do not work at all.

**Comment by davidlawson** [comment]
This is due to an old SSL certificate installed on the server, I'll fix this up now.

**Comment by davidlawson** [comment]
@jhamwood I've renewed the SSL certificate, let me know if the issue is fixed!

**Comment by jhamwood** [comment]
It's working perfectly on our Pro now, thank you! I'll reopen the issue if any issues arise on the other iPad Pro.
